config/routes.rb
Rails.application.routes.draw do
  root 'search#index'
  get 'search' => 'search#index'
  resources :skills
  resources :workers

end

app/models/customer.rb
class Customer < User

end

app/models/search.rb
class Search
  include ActiveModel::Model

  attr_accessor :skills

  def initialize(args = {})
    @skills = args[:skills] if args[:skills].present?
  end
end

app/models/skill.rb
class Skill
  include Neo4j::ActiveNode

  property :keyword, type: String, index: :exact

  has_many :in, :workers, type: 'HAS_SKILLS', unique: true

  validates :keyword, presence: true, length: { minimum: 2, maximum: 30 }, uniqueness: true

  scope :default_order, -> { order(keyword: :asc) }
end

app/models/user.rb
class User
  include Neo4j::ActiveNode

  property :email, type: String, constraint: :unique
  property :name, type: String

  validates :email, presence: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/ }
  validates :name, presence: true
  #validates :password, length: { minimum: 6 }, allow_nil: true
end

app/models/worker.rb
class Worker < User
  has_many :out, :skills, type: 'HAS_SKILLS', unique: true

  def skills_string
    skill_keywords.join(', ')
  end

  def skill_keywords
    skills.map(&:keyword)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
end

app/controllers/search_controller.rb
class SearchController < ApplicationController

  def index
    @search = Search.new(search_params)
    @found_workers = []
    if search_params
      @found_workers = Match.call(skill_keywords: search_params[:skills])
    end
  end

  private

  def search_params
    search_params = params[:search].present? ? params[:search] : {skills: []}
    search_params
  end
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  before_action :set_skill, only: [:show, :edit, :update, :destroy]

  # GET /skills
  def index
    @skills = Skill.all
  end

  # GET /skills/1
  def show
  end

  # GET /skills/new
  def new
    @skill = Skill.new
  end

  # GET /skills/1/edit
  def edit
  end

  # POST /skills
  def create
    @skill = Skill.new(skill_params)

    if @skill.save
      redirect_to @skill, notice: 'Skill was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /skills/1
  def update
    if @skill.update(skill_params)
      redirect_to @skill, notice: 'Skill was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /skills/1
  def destroy
    @skill.destroy
    redirect_to skills_url, notice: 'Skill was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_skill
      @skill = Skill.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def skill_params
      params[:skill]
    end
end

app/controllers/workers_controller.rb
class WorkersController < ApplicationController
  before_action :set_worker, only: [:show, :edit, :update, :destroy]


  # GET /workers
  def index
    @workers = Worker.all
  end

  # GET /workers/1
  def show
  end

  # GET /workers/new
  def new
    @worker = Worker.new
  end

  # GET /workers/1/edit
  def edit
  end

  # POST /workers
  def create
    @worker = Worker.new(worker_params)
    update_skills(worker_params)
    if @worker.save
      redirect_to @worker, notice: 'Worker was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /workers/1
  def update
    update_skills(worker_params)
    if @worker.update(worker_params)
      redirect_to @worker, notice: 'Worker was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /workers/1
  def destroy
    @worker.destroy
    redirect_to workers_url, notice: 'Worker was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_worker
      #eager load skills to avoid n+1 query problem
      @worker = Worker.where(uuid: params[:id]).with_associations(:skills).first
    end

    # Only allow a trusted parameter "white list" through.
    def worker_params
      params[:worker]
    end

    def update_skills(worker_params)
      keywords = worker_params.delete(:skills).try(:reject, &:blank?)
      if keywords.present?
        skills = Skill.where(keyword: keywords)
        # convert to set to ignore order of skills
        if skills.to_set != @worker.skills.to_set
          Rails.logger.info("Updating #{@worker.name}'s' skills")
          # TODO: should be refactored to only add/remove those skills that changed
          @worker.skills = skills
        end
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def skills_options
    options = Skill.all.map{|s| [s.keyword, s.keyword]}
    options
  end
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/helpers/workers_helper.rb
module WorkersHelper
end

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    = content_tag :div, msg, :class => "flash_#{name}"

app/views/layouts/_navigation.html.haml
%ul.nav
  %li= link_to 'Home', root_path
  = render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.haml
//add navigation links to this file
= link_to('Workers', workers_path)
= link_to('Skills', skills_path)

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Matcher'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Matcher'}"}
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    %header
      = render 'layouts/navigation'
    %main{:role => "main"}
      = render 'layouts/messages'
      = yield

app/views/search/_form.html.haml
= form_for @search, url: '/search', method: 'GET' do |f|
  - if @search.errors.any?
    #error_explanation
      %h2= "#{pluralize(@search.errors.count, "error")} prohibited this match_worker from being saved:"
      %ul
        - @search.errors.full_messages.each do |msg|
          %li= msg
  = f.label(:skills, 'Select skills:')
  %br
  = f.select(:skills, options_for_select(skills_options, @search.skills), {}, {multiple: true})
  .actions
    = f.submit 'Search'

app/views/search/index.html.haml
%h1 Search Matching Workers

= render 'form'

- if(@search.skills.present?)
  %h3= "Found #{@found_workers.count} matching workers"
%table
  %thead
    %tr
      %th
      %th
      %th
      %th

  %tbody
    - @found_workers.each do |worker|
      %tr
        %td= "#{worker.name}"
        %td= link_to 'Show', worker_path(worker)
%br

app/views/skills/_form.html.haml
= form_for @skill do |f|
  - if @skill.errors.any?
    #error_explanation
      %h2= "#{pluralize(@skill.errors.count, "error")} prohibited this skill from being saved:"
      %ul
        - @skill.errors.full_messages.each do |msg|
          %li= msg

  = f.label(:keyword)
  = f.text_field(:keyword)
  .actions
    = f.submit 'Save'

app/views/skills/edit.html.haml
%h1 Editing skill

= render 'form'

= link_to 'Show', @skill
\|
= link_to 'Back', skills_path

app/views/skills/index.html.haml
%h1 Listing skills

%table
  %thead
    %tr
      %th
      %th
      %th
      %th

  %tbody
    - @skills.each do |skill|
      %tr
        %td= skill.keyword
        %td= link_to 'Show', skill
        %td= link_to 'Edit', edit_skill_path(skill)
        %td= link_to 'Destroy', skill, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Skill', new_skill_path

app/views/skills/new.html.haml
%h1 New skill

= render 'form'

= link_to 'Back', skills_path

app/views/skills/show.html.haml
%h2 Skill
%h4=@skill.keyword


= link_to 'Edit', edit_skill_path(@skill)
\|
= link_to 'Back', skills_path

app/views/workers/_form.html.haml
= form_for @worker do |f|
  - if @worker.errors.any?
    #error_explanation
      %h2= "#{pluralize(@worker.errors.count, "error")} prohibited this worker from being saved:"
      %ul
        - @worker.errors.full_messages.each do |msg|
          %li= msg

  = f.label('Name:')
  = f.text_field(:name)
  = f.label('Email:')
  = f.email_field(:email)
  %br
  %br
  = f.label('Choose skills:')
  %br
  = f.select(:skills, options_for_select(skills_options, @worker.skill_keywords), {}, {multiple: true})
  .actions
    = f.submit 'Save'

app/views/workers/edit.html.haml
%h1 Editing worker

= render 'form'

= link_to 'Show', @worker
\|
= link_to 'Back', workers_path

app/views/workers/index.html.haml
%h1 Listing workers

%table
  %thead
    %tr
      %th
      %th
      %th

  %tbody
    - @workers.each do |worker|
      %tr
        %td= worker.name
        %td= link_to 'Show', worker
        %td= link_to 'Edit', edit_worker_path(worker)
        %td= link_to 'Destroy', worker, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Worker', new_worker_path

app/views/workers/new.html.haml
%h1 New worker

= render 'form'

= link_to 'Back', workers_path

app/views/workers/show.html.haml
%h1 Worker
%h4= "#{@worker.name} (#{@worker.email})"
= "Skills: #{@worker.skills_string}"

%br
%br
= link_to 'Edit', edit_worker_path(@worker)
\|
= link_to 'Back', workers_path